from typing import Dict, Optional
from datetime import datetime
from market_hours import MarketHours


class ReportGenerator:
    def __init__(self, market_service):
        self.market_service = market_service
        self.market_hours = MarketHours()
    
    def generate_report(self, sector: str, market_data: Dict) -> str:
        report_lines = []
        
        report_lines.append(f"# {sector} Sector Analysis")
        report_lines.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
        
        market_status = self.market_hours.get_market_status_message()
        if market_status:
            report_lines.append(f"> {market_status}\n")
        
        summary = market_data.get("summary", {})
        tickers = market_data.get("tickers", [])
        
        if summary and any(summary.values()):
            report_lines.append("## Market Overview\n")
            
            avg_change = summary.get("avgChangePercent", 0)
            trend = "📈 Bullish" if avg_change > 0 else "📉 Bearish" if avg_change < 0 else "➡️ Neutral"
            
            report_lines.append(f"- **Market Sentiment:** {trend}")
            report_lines.append(f"- **Average Change:** {avg_change:.2f}%")
            report_lines.append(f"- **Gaining Stocks:** {summary.get('gaining', 0)}")
            report_lines.append(f"- **Losing Stocks:** {summary.get('losing', 0)}")
            total_volume = summary.get('totalVolume', 0)
            if total_volume and total_volume > 0:
                report_lines.append(f"- **Total Volume:** {self._format_number(total_volume)}\n")
            else:
                report_lines.append("")
        
        if tickers:
            report_lines.append("## Key Stocks\n")
            
            for ticker in tickers[:10]:
                if ticker.get("price", 0) > 0:
                    symbol = ticker.get("symbol", "N/A")
                    price = ticker.get("price", 0)
                    change = ticker.get("change", 0)
                    change_pct = ticker.get("changePercent", 0)
                    volume = ticker.get("volume", 0)
                    
                    change_indicator = "🟢" if change > 0 else "🔴" if change < 0 else "⚪"
                    
                    report_lines.append(f"### {symbol} {change_indicator}")
                    report_lines.append(f"- **Price:** ₹{price:.2f}")
                    report_lines.append(f"- **Change:** ₹{change:.2f} ({change_pct:.2f}%)")
                    
                    if ticker.get("high", 0) > 0 and ticker.get("low", 0) > 0:
                        report_lines.append(f"- **Range:** ₹{ticker.get('low', 0):.2f} - ₹{ticker.get('high', 0):.2f}")
                    
                    if volume > 0:
                        report_lines.append(f"- **Volume:** {self._format_number(volume)}")
                    
                    report_lines.append("")
        
        if not tickers or not any(t.get("price", 0) > 0 for t in tickers):
            report_lines.append("## Data Availability\n")
            report_lines.append("⚠️ Limited market data available for this sector at this time.")
            report_lines.append("Please try again later or verify the sector name.\n")
        
        report_lines.append("---")
        report_lines.append(f"\n*Report generated by Sector Analysis API*")
        
        return "\n".join(report_lines)
    
    def _format_number(self, num: float) -> str:
        if num >= 1_000_000_000:
            return f"{num / 1_000_000_000:.2f}B"
        elif num >= 1_000_000:
            return f"{num / 1_000_000:.2f}M"
        elif num >= 1_000:
            return f"{num / 1_000:.2f}K"
        else:
            return f"{num:.0f}"

